### ISSUE TITLE
Kyverno Policy reports are not shown in UI

### ISSUE THREAD

**Issue by m-yosefpor** [kyverno/policy-reporter-kyverno-plugin#7]
I have deployed the kyverno policy reporter with official helm charts with the following values:

```  
  ui:
    enabled: true
    plugins:
      kyverno: true
    ingress:
      enabled: true
      hosts:
      - host: myhost.example.com
        paths:
        - path: /
  kyvernoPlugin:
    enabled: true
```

And I can see the policies in UI:
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/47300215/137650062-c8e84a49-4671-466e-8305-0a479c2bc3fb.png">

Also I can see the policy warnings in the `Logs` section:

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/47300215/137650093-f2ca3088-8354-417a-ae0a-f8382c3e2313.png">

However, there are no reports in other part of the UI:
<img width="736" alt="image" src="https://user-images.githubusercontent.com/47300215/137650124-52c64d14-3d8c-49d6-8c8f-f931afab9710.png">

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/47300215/137650143-93df4190-988a-453a-950c-5465439c75d8.png">
